opt_in_rules:
    - attributes
    - array_init
    - closing_brace
    - closure_end_indentation
    - closure_parameter_position
    - closure_spacing
    - collection_alignment
    - colon
    - comma
    - compiler_protocol_init
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - control_statement
    - convenience_type
    - cyclomatic_complexity
    - discouraged_direct_init
    - duplicate_imports
    - empty_collection_literal
    - empty_count
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - empty_string
    - empty_xctest_method
    - explicit_init
    - fatal_error_message
    - file_length
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - for_where
    - force_cast
    - force_try
    - function_body_length
    - function_parameter_count
    - identifier_name
    - identical_operands
    - implicit_getter
    - implicit_return
    - is_disjoint
    - joined_default_parameter
    - last_where
    - leading_whitespace
    - legacy_multiple
    - legacy_random
    - line_length
    - literal_expression_end_indentation
    - multiline_arguments
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - modifier_order
    - nesting
    - no_extension_access_modifier
    - no_space_in_method_call
    - opening_brace
    - operator_usage_whitespace
    - overridden_super_call
    - prefer_self_type_over_type_of_self
    - private_action
    - private_outlet
    - private_over_fileprivate
    - protocol_property_accessors_order
    - reduce_boolean
    - reduce_into
    - redundant_discardable_let
    - redundant_objc_attribute
    - redundant_optional_initialization
    - redundant_set_access_control
    - redundant_string_enum_value
    - redundant_type_annotation
    - redundant_void_return
    - return_arrow_whitespace
    - shorthand_operator
    - sorted_first_last
    - sorted_imports
    - statement_position
    - static_operator
    - syntactic_sugar
    - todo
    - toggle_bool
    - trailing_newline
    - trailing_semicolon
    - trailing_whitespace
    - type_body_length
    - type_name
    - unavailable_function
    - unneeded_break_in_switch
    - unneeded_parentheses_in_closure_argument
    - unused_closure_parameter
    - unused_control_flow_label
    - unused_enumerated
    - unused_optional_binding
    - unused_setter_value
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - vertical_whitespace
    - vertical_whitespace_between_cases
    - vertical_whitespace_closing_braces
    - void_return
    - weak_delegate
    - xct_specific_matcher
    - xctfail_message
    - yoda_condition

disabled_rules:
    - trailing_comma
    - large_tuple
    - void_function_in_ternary
    
analyzer_rules:
    - explicit_self
    - unused_import
    
excluded:
  - Pods

line_length:
  warning: 150
  error: 250
  ignores_urls: true
  ignores_comments: true

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 500
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 7
  error: 15
  ignores_case_statements: true

function_body_length:
  warning: 60
  error: 200

identifier_name:
  min_length:
    error: 0
    warning: 0
  max_length:
    error: 64
    warning: 48

modifier_order:
  preferred_modifier_order: ["acl", "setterACL", "override", "mutators", "final", "dynamic", "convenience", "required", "lazy", "owned", "typeMethods"]

nesting:
  type_level: 3
  function_level: 5

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 65

attributes:
  always_on_same_line: ["@IBAction", "@IBOutlet", "@Environment", "@Query"]
  always_on_line_above: ["@available", "@convention", "@discardableResult", "@dynamicMemberLookup", "@objcMembers", "@IBDesignable", "@IBInspectable", "@objc", "@NSCopying", "@NSManaged", "@inlinable", "@nonobjc", "@usableFromInline"]
